### ISSUE TITLE
Failure on installation

### ISSUE THREAD

**Issue by mailanetworks** [mdshemul48/fiber-network-management-tool-for-isp#2]
Hi,

I have installed the project, but database authentication does not work.
I have setup a mongo database and I can connect to it use the credentials set in .env
But when I run:
```
fiberdocs/backend$ npm start

> circle_geo_map@1.0.0 start /var/www/fiberdocs/backend
> node server.js

(node:4215) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error connecting to database:  MongoServerError: bad auth : Authentication failed.
    at Connection.onMessage (/var/www/fiberdocs/backend/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/var/www/fiberdocs/backend/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (events.js:400:28)
    at processIncomingData (/var/www/fiberdocs/backend/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/var/www/fiberdocs/backend/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:731:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}

```

**Comment by mdshemul48** [comment]
It seems that there may be an issue with the MongoDB database credentials you provided.
